"""Application settings.

Resolved from environment variables via ``pydantic-settings``. Kept
in a single module so every consumer imports from one place.

Settings are read once at application startup (Pydantic's ``Settings``
caches the parsed values for the process lifetime). Tests override
via dependency injection, not environment mutation — see
``tests/auth/conftest.py``.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Literal

from pydantic import Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Global settings.

    Env vars are prefixed ``ACCOUNTING_PARSER_`` so they don't
    collide with CI / runtime env pollution. Boolean flags use
    ``1`` / ``0`` rather than ``true`` / ``false`` to avoid
    ambiguity across shells.
    """

    model_config = SettingsConfigDict(
        env_prefix="ACCOUNTING_PARSER_",
        env_file=".env",
        env_file_encoding="utf-8",
        # Let env vars override .env for test isolation.
        extra="ignore",
        case_sensitive=False,
    )

    # ---- Database ---------------------------------------------
    db_url: str = Field(
        default="postgresql+psycopg://app_user:app_user@localhost:5432/accounting_parser",
        description=(
            "PostgreSQL DSN. Role MUST have NOBYPASSRLS (app_user). "
            "Enforced at startup by assert_app_user_has_no_bypass_rls."
        ),
    )

    # ---- Auth adapter selection -------------------------------
    auth_adapter: Literal["authentik", "cognito", "memory"] = Field(
        default="authentik",
        description=(
            "Which AuthAdapter implementation to instantiate. "
            "'authentik' is the self-hosted default, 'cognito' is a stub, "
            "'memory' is an in-process implementation used only in tests."
        ),
    )

    # ---- Authentik adapter config -----------------------------
    authentik_base_url: str = Field(
        default="http://authentik:9443",
        description="Authentik base URL (container-internal by default).",
    )
    authentik_client_id: str = Field(default="accounting-parser")
    authentik_api_token: SecretStr = Field(default=SecretStr(""))
    authentik_jwks_url: str = Field(
        default="http://authentik:9443/application/o/accounting-parser/jwks/"
    )
    authentik_audience: str = Field(default="accounting-parser")
    authentik_issuer: str = Field(default="http://authentik:9443/application/o/accounting-parser/")

    # ---- Our session signing ----------------------------------
    # We mint session tokens after the passkey has been verified;
    # these settings are the keys used for signing + verifying
    # those tokens. EdDSA / Ed25519 per adapter design.
    session_signing_key_pem: SecretStr = Field(
        default=SecretStr(""),
        description=(
            "PEM-encoded Ed25519 private key for signing session tokens. "
            "Generated by the installer; never ships with source. "
            "In tests, fixtures set a deterministic key."
        ),
    )
    session_signing_kid: str = Field(
        default="session-signing-v1",
        description="key id that appears in session token JWT headers.",
    )
    session_duration_seconds: int = Field(
        default=24 * 60 * 60,
        ge=300,
        le=30 * 24 * 60 * 60,
        description=(
            "Session lifetime in seconds. Default 24h per R26 comments; "
            "minimum 5 min, maximum 30 days (hard upper bound)."
        ),
    )

    # ---- Magic link ---------------------------------------------
    magic_link_ttl_seconds: int = Field(default=15 * 60, ge=60, le=60 * 60)

    # ---- Firm instance settings (single-firm fork) ------------
    firm_rp_name: str = Field(
        default="Accounting Parser",
        description="Relying Party display name for WebAuthn ceremonies.",
    )
    firm_rp_id: str = Field(
        default="localhost",
        description=(
            "Relying Party ID for WebAuthn. MUST match the domain users "
            "visit. Installer prompts for this; default is 'localhost' "
            "for dev only. Production: the configured FQDN."
        ),
    )


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return the process-wide settings singleton.

    ``lru_cache`` handles the singleton; tests override by calling
    ``get_settings.cache_clear()`` after setting env vars, or by
    injecting a Settings instance directly.
    """
    return Settings()
